version: '3'
services:
  # 서비스명
  mysql:
    # 사용할 이미지
    image: mysql
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너명 설정
    container_name: mysql
    # 접근 포트 설정(컨테이너 외부:컨테이너 내부)
    ports:
      - "3306:3306"
    # 환경 변수 설정
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: database
      TZ: Asia/Seoul
    # 명령어 설정
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    # 볼륨 설정
    volumes:
      - D:\docker\mysql\data:\var\lib\mysql



# 컨테이너 생성 및 실행
# docker-compose -f mysql-docker-compose.yml up -d

# 컨테이너 백그라운드로 띄우기
# docker-compose up -d

# 도커 컴포즈 컨테이너들 포어그라운드로 띄우기
# docker-compose up

# 도커 컴포즈 컨테이너들을 내리기
# docker-compose down

# 도커 컴포즈 컨테이너들을 다시 시작하기
# docker-compose restart

# 도커 컴포즈 컨테이너들의 상태 확인
# docker-compose ps

# 도커 컴포즈 설정을 확인
# docker-compose config